import { BRAND, escape as e, safeURL, formatDate } from './content.mjs';
const join = values => values.filter(Boolean).join('');
const link = (href, text, cls = '') => `<a href="${e(safeURL(href))}"${cls ? ` class="${cls}"` : ''}>${e(text)}</a>`;
const badge = text => `<span class="status status-${String(text).toLowerCase().replaceAll(' ', '-')}">${e(text)}</span>`;
const date = value => value ? `<time datetime="${e(value)}">${e(formatDate(value))}</time>` : '';
export function richText(value) {
  // A deliberately small plain-text markup: escape first; no authored HTML or script survives.
  return String(value || '').split(/\n\s*\n/).filter(Boolean).map(p => `<p>${e(p).replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\*([^*]+)\*/g, '<em>$1</em>').replaceAll('\n', '<br>')}</p>`).join('');
}
export function picture(media, { hero = false, sizes = '(max-width: 650px) 100vw, (max-width: 1000px) 50vw, 33vw', cls = '' } = {}) {
  if (!media) return '<div class="missing-photo" role="img" aria-label="No photograph available"><img src="/brand/icon.webp" width="96" height="96" alt=""></div>';
  const variants = Object.entries(media.variants || {}).map(([width, src]) => `${e(safeURL(src))} ${width}w`).join(', ');
  return `<img class="${cls}" src="${e(safeURL(media.variants?.[800] || media.src))}" ${variants ? `srcset="${variants}" sizes="${e(sizes)}"` : ''} width="${Number(media.width)}" height="${Number(media.height)}" alt="${e(media.alt)}" ${hero ? 'fetchpriority="high" loading="eager"' : 'loading="lazy"'} decoding="async" style="object-position:${(media.focalPoint?.x ?? .5) * 100}% ${(media.focalPoint?.y ?? .5) * 100}%" data-media-image>`;
}
export function viewContext(content) {
  const media = id => content.media.find(m => m.id === id);
  const place = id => content.places.find(p => p.id === id);
  const settings = content.settings[0];
  const updates = [...content.updates].filter(u => u.state === 'published').sort((a, b) => String(b.publishedAt).localeCompare(String(a.publishedAt)));
  return { media, place, settings, updates };
}
export function placeCard(place, content, { compact = false } = {}) {
  const { media } = viewContext(content);
  return `<article class="place-card ${compact ? 'compact' : ''}">${link(`/places/${place.slug}/`, '', 'card-image').replace('</a>', `${picture(media(place.coverId))}</a>`)}<div class="card-copy"><h3>${link(`/places/${place.slug}/`, place.name)}</h3>${badge(place.status)}</div></article>`;
}
function updateCard(update, content) {
  const { media, place } = viewContext(content);
  const p = place(update.placeId);
  return `<article class="update-card"><a class="card-image" href="/journal/${e(update.slug)}/">${picture(media(update.mediaIds?.[0]))}</a><div><p class="eyebrow">${date(update.publishedAt)} · ${e(viewContext(content).place(update.placeId)?.name || '')}</p><h3>${link(`/journal/${update.slug}/`, update.title)}</h3><p class="meta">${e(update.author)}${p ? ` · ${link(`/places/${p.slug}/`, p.name)}` : ''}</p></div></article>`;
}
function articleCard(article, content) {
  const { media } = viewContext(content);
  return `<article class="update-card"><a class="card-image" href="${e(safeURL(article.url))}">${picture(media(article.imageId))}</a><div><p class="eyebrow">${date(article.date)} · Substack</p><h3>${link(article.url, article.title)}</h3><p>${link(article.url, 'Read on Substack ↗', 'quiet-link')}</p></div></article>`;
}
function intro(kicker, title, description, extra = '') { return `<header class="page-intro container"><h1>${e(title)}</h1>${extra}</header>`; }
function follow(settings) { return ''; }
function select(name, label, options, selected = '') { return `<label>${e(label)}<select name="${name}"><option value="">All ${e(label.toLowerCase())}</option>${options.map(option => { const [value, text] = Array.isArray(option) ? option : [option, option]; return `<option value="${e(value)}" ${selected === value ? 'selected' : ''}>${e(text)}</option>`; }).join('')}</select></label>`; }
function filterForm(fields, action, query, extra = '') { return `<form class="filters" action="${action}" method="get" data-filters><label>Search<input type="search" name="q" value="${e(query.get('q') || '')}" placeholder="Search"></label>${fields}${extra}<button class="button small" type="submit">Apply filters</button>${link(action, 'Clear filters', 'quiet-link')}</form>`; }
function photoLink(m, place, { index = 0, grid = true } = {}) { return `<figure class="${grid ? 'gallery-card' : 'main-photograph'}" id="photo-${e(m.id)}"><a href="${e(safeURL(m.src))}" data-photo data-id="${e(m.id)}" data-caption="${e(m.caption)}" data-credit="${e(m.credit)}" data-place-url="${place ? `/places/${e(place.slug)}/` : '/gallery/'}" data-place="${e(place?.name || 'Gallery')}" aria-label="Open photograph: ${e(m.alt)}">${picture(m, { hero: !grid && index === 0, sizes: grid ? '(max-width: 650px) 100vw, 50vw' : '(max-width: 1000px) 100vw, 1200px' })}<span class="expand-label" aria-hidden="true">View photograph ↗</span></a><figcaption><span>${e(m.caption || m.alt)}</span>${place ? link(`/places/${place.slug}/`, place.name) : ''}</figcaption></figure>`; }
function placeGallery(images, place) {
  if (!images.length) return picture(null);
  return `<section class="place-gallery" aria-label="${e(place.name)} photographs"><div data-gallery-main>${photoLink(images[0], place, { grid: false })}</div>${images.length > 1 ? `<div class="thumbnail-strip" aria-label="Choose a photograph">${images.map((m, i) => `<a href="${e(safeURL(m.src))}" data-thumbnail data-id="${e(m.id)}" data-caption="${e(m.caption)}" data-credit="${e(m.credit)}" aria-label="Show photograph ${i + 1}: ${e(m.alt)}" ${i === 0 ? 'aria-current="true"' : ''}>${picture(m, { sizes: '120px' })}</a>`).join('')}</div>` : ''}</section>`;
}
function stageRow(s, content) {
  const p = content.places.find(p => p.id === s.placeId);
  return `<article class="stage-row" id="stage-${e(s.id)}"><div><p class="eyebrow">${p ? link(`/places/${p.slug}/`, p.name) : 'Project notes'} · ${e(s.category)}</p><h3>${link(`/builds/${s.id}/`, s.publicTitle)}</h3><details><summary>Build notes</summary>${richText(s.notes)}${s.estimatedHours ? `<p>Estimated hours: ${e(s.estimatedHours)}</p>` : ''}</details></div><div class="stage-meta">${badge(s.status)}${date(s.completedAt)}${s.updatedAt ? `<span>Updated ${date(s.updatedAt)}</span>` : ''}</div></article>`;
}
export function renderPage(pathname, content, query = new URLSearchParams()) {
  const path = `/${pathname.split('/').filter(Boolean).join('/')}/`.replace('//', '/');
  const { settings, media, place, updates } = viewContext(content);
  let title = '', description = '', body = '', image = settings.heroId, status = 200;
  const selectedPlaces = settings.featuredPlaceIds.map(place).filter(Boolean);
  if (path === '/') {
    title = BRAND; description = settings.introduction;
    const heroPlace = content.places.find(p => p.mediaIds.includes(settings.heroId)) || selectedPlaces[0];
    const current = content.stages.find(s => s.id === settings.focusStageId);
    const latestArticle = [...content.articles].sort((a,b) => b.date.localeCompare(a.date))[0];
    const recent = latestArticle && (!updates[0] || latestArticle.date > updates[0].publishedAt) ? articleCard(latestArticle, content) : updates[0] ? updateCard(updates[0], content) : '';
    body = `<section class="home-hero">${picture(media(settings.heroId), { hero: true, sizes: '100vw', cls: 'hero-image' })}<div class="hero-shade"></div><div class="container hero-content"><h1><img src="/brand/logo.webp" width="1200" height="630" alt="Gielinor: Reforged" fetchpriority="high"></h1><p class="hero-purpose">RuneScape’s Gielinor, rebuilt in Minecraft.</p><div class="actions">${link('/explore/', 'Explore', 'button brass')}${link('/gallery/', 'Gallery', 'button ghost')}</div></div><div class="hero-caption container">${heroPlace ? link(`/places/${heroPlace.slug}/`, `${heroPlace.name} ↗`) : ''}</div></section>
    <section class="container section home-places"><div class="section-heading"><h2>Places</h2>${link('/explore/', 'View all →', 'quiet-link')}</div><div class="place-grid">${selectedPlaces.map(p => placeCard(p, content)).join('')}</div></section>
    <section class="recent-section"><div class="container section"><div class="section-heading"><h2>Latest</h2>${link('/journal/', 'Journal →', 'quiet-link')}</div>${recent}</div></section>
    <section class="container section atlas-preview"><a href="/explore/#atlas" class="map-preview">${picture(media(settings.mapId), { sizes: '(max-width: 768px) 100vw, 1200px' })}<span class="map-label">Open atlas ↗</span></a></section>`;
  } else if (path === '/explore/') {
    title = 'Explore'; description = 'Places in Gielinor: Reforged.';
    const filters = select('region', 'Regions', content.regions.map(r => [r.id, r.name]), query.get('region')) + select('status', 'Statuses', ['Built', 'In progress', 'Planned'], query.get('status')) + select('layer', 'Layers', [['surface', 'Above ground'], ['underground', 'Underground']], query.get('layer'));
    const matches = content.places.filter(p => (!query.get('q') || `${p.name} ${p.summary}`.toLowerCase().includes(query.get('q').toLowerCase())) && (!query.get('region') || p.regionId === query.get('region')) && (!query.get('status') || p.status === query.get('status')) && (!query.get('layer') || (p.category === 'underground') === (query.get('layer') === 'underground')));
    const chosen = place(query.get('place'));
    body = intro('The atlas', title, description, `<p class="intro-links">${link('/regions/misthalin/', 'Misthalin')}${link('/progress/', 'Progress')}${link('/search/?saved=1', 'Saved places')}</p>`) + `<div class="container">${filterForm(filters, '/explore/', query)}<div class="atlas-layout"><section class="directory" aria-label="Place directory"><p class="results" role="status">${matches.length} places${query.get('region') ? ` in ${e(content.regions.find(r => r.id === query.get('region'))?.name || query.get('region'))}` : ''}</p>${matches.length ? matches.map(p => placeCard(p, content, { compact: true })).join('') : '<div class="empty-state"><h2>No matching places</h2><a href="/explore/">Clear filters</a></div>'}</section><details class="atlas-map" id="atlas" ${chosen ? 'open' : ''}><summary>Open map</summary><div class="map-controls" aria-label="Map controls"><button type="button" data-map-zoom=".25" aria-label="Zoom map in">+</button><button type="button" data-map-zoom="-.25" aria-label="Zoom map out">−</button><button type="button" data-map-reset>Reset</button><button type="button" data-map-pan="-120,0" aria-label="Pan left">←</button><button type="button" data-map-pan="120,0" aria-label="Pan right">→</button><button type="button" data-map-pan="0,-120" aria-label="Pan up">↑</button><button type="button" data-map-pan="0,120" aria-label="Pan down">↓</button></div><div class="map-viewport" tabindex="0" aria-label="Scrollable map of Gielinor"><div class="map-canvas" data-focus-x="${chosen?.pin?.x ?? .721}" data-focus-y="${chosen?.pin?.y ?? .453}">${picture(media(settings.mapId), { sizes: '900px' })}${matches.filter(p => p.pin).map(p => `<a class="map-pin ${chosen?.id === p.id ? 'selected' : ''}" style="left:${p.pin.x * 100}%;top:${p.pin.y * 100}%" href="/explore/?${e(new URLSearchParams({ ...Object.fromEntries(query), place: p.id }).toString())}#atlas" aria-label="Select ${e(p.name)}: ${e(p.status)}"><span aria-hidden="true">${p.category === 'underground' ? '◇' : '◆'}</span><span class="pin-label">${e(p.name)}</span></a>`).join('')}</div></div>${chosen ? `<aside class="pin-detail"><a class="close-selection" href="/explore/?${e(new URLSearchParams(Object.fromEntries([...query].filter(([k]) => k !== 'place'))).toString())}#atlas" aria-label="Close place selection">Close ×</a>${placeCard(chosen, content, { compact: true })}</aside>` : ''}</details></div><details class="region-overview"><summary>Regions</summary><div class="region-grid">${content.regions.filter(r => r.id !== 'misthalin').map(r => `<article><h3>${e(r.name)}</h3>${badge(r.status)}</article>`).join('')}</div></details></div>`;
  } else if (path.startsWith('/places/')) {
    const p = content.places.find(p => `/places/${p.slug}/` === path);
    if (!p) return notFound();
    title = p.name; description = p.summary; image = p.coverId;
    const history = updates.filter(u => u.placeId === p.id), images = p.mediaIds.map(media).filter(Boolean);
    body = intro(content.regions.find(r => r.id === p.regionId)?.name || 'Gielinor', title, description, `<div class="place-meta">${badge(p.status)}${history[0] ? `<span>${date(history[0].publishedAt)}</span>` : ''}<button type="button" class="save-place" data-save="${e(p.id)}" aria-pressed="false">Save this place</button></div>`) + `<div class="container">${placeGallery(images, p)}<div class="place-story section"><section><h2>Updates</h2>${history.length ? history.map(u => `<article class="history-entry"><p class="eyebrow">${date(u.publishedAt)} · ${e(u.kind || 'Build update')}</p><h3>${link(`/journal/${u.slug}/`, u.title)}</h3></article>`).join('') : ''}<details class="stage-details"><summary>Build stages (${p.stageIds.length})</summary>${p.stageIds.map(id => content.stages.find(s => s.id === id)).filter(Boolean).map(s => stageRow(s, content)).join('')}</details></section><aside class="place-aside">${link(`/explore/?place=${p.id}#atlas`, 'Map ↗')}${link(settings.instagram, 'Instagram ↗')}</aside></div><section class="section"><div class="section-heading"><h2>Nearby</h2></div><div class="place-grid">${(p.relatedIds || []).map(place).filter(Boolean).map(p => placeCard(p, content)).join('')}</div></section></div>${follow(settings)}`;
  } else if (path.startsWith('/builds/')) {
    const stage = content.stages.find(s => `/builds/${s.id}/` === path);
    if (!stage) return notFound();
    const p = place(stage.placeId); title = stage.publicTitle; description = stage.scope; image = stage.mediaIds[0];
    body = intro('Original build log', title, description, `<p>${badge(stage.status)} ${stage.completedAt ? `Completed ${date(stage.completedAt)}` : ''}</p>`) + `<article class="container reading section"><p>${p ? link(`/places/${p.slug}/`, `Part of ${p.name} →`) : link('/about/', 'Project notes →')}</p>${richText(stage.notes)}${stage.estimatedHours ? `<p class="note">Estimated hours: ${e(stage.estimatedHours)}</p>` : ''}${stage.mediaIds.map(media).filter(Boolean).map(m => photoLink(m, p)).join('')}<p>${link('/progress/', 'Back to progress', 'button')}</p></article>`;
  } else if (path === '/progress/') {
    title = 'Progress'; description = 'Gielinor: Reforged build progress.';
    const filters = select('region', 'Regions', [['general', 'Project notes'], ...content.regions.map(r => [r.id, r.name])], query.get('region')) + select('type', 'Types', ['building', 'landscape', 'infrastructure', 'monument', 'other'], query.get('type')) + select('status', 'Statuses', [['In progress', 'Working on'], ['Planned', 'Next'], ['Built', 'Finished']], query.get('status'));
    let stages = content.stages.filter(s => (!query.get('q') || `${s.publicTitle} ${s.scope}`.toLowerCase().includes(query.get('q').toLowerCase())) && (!query.get('region') || s.regionId === query.get('region')) && (!query.get('type') || s.category === query.get('type')) && (!query.get('status') || s.status === query.get('status')) && (query.get('project') === 'yes' || s.placeId));
    if (query.get('sort') === 'oldest') stages.sort((a, b) => (a.updatedAt || a.completedAt || '9999').localeCompare(b.updatedAt || b.completedAt || '9999'));
    else if (query.get('sort') === 'name') stages.sort((a, b) => a.publicTitle.localeCompare(b.publicTitle));
    else stages.sort((a, b) => (b.updatedAt || b.completedAt || '').localeCompare(a.updatedAt || a.completedAt || ''));
    const focus = content.stages.find(s => s.id === settings.focusStageId);
    body = intro('Progress', title, description) + `<div class="container section-top">${focus ? `<aside class="focus-band"><p class="eyebrow">Current focus</p><h2>${link(`/builds/${focus.id}/`, focus.publicTitle)}</h2></aside>` : ''}${filterForm(filters, '/progress/', query, `${select('sort', 'Sort order', [['latest', 'Latest recorded change'], ['oldest', 'Oldest recorded change'], ['name', 'Name']], query.get('sort'))}<label class="checkbox"><input type="checkbox" name="project" value="yes" ${query.get('project') === 'yes' ? 'checked' : ''}>Include project notes</label><label>View<select name="view"><option value="list">List</option><option value="board" ${query.get('view') === 'board' ? 'selected' : ''}>Board</option></select></label>`)}<p class="results" role="status">${stages.length} stages</p><div class="progress-groups ${query.get('view') === 'board' ? 'board-view' : ''}">${[['In progress', 'Working on'], ['Planned', 'Next'], ['Built', 'Finished']].filter(([value]) => !query.get('status') || query.get('status') === value).map(([value, label]) => `<section class="progress-group"><h2>${label} <span>${stages.filter(s => s.status === value).length}</span></h2>${stages.filter(s => s.status === value).map(s => stageRow(s, content)).join('') || '<p class="empty-state">No stages in this view. <a href="/progress/">Clear filters</a></p>'}</section>`).join('')}</div></div>`;
  } else if (path === '/gallery/') {
    title = 'Gallery'; description = 'Gielinor: Reforged photographs.';
    const selection = settings.galleryMediaIds.map(media).filter(Boolean).map(m => ({ m, p: content.places.find(p => p.mediaIds.includes(m.id)) })).filter(({ m, p }) => (!query.get('place') || p?.id === query.get('place')) && (!query.get('subject') || m.subject === query.get('subject')) && (!query.get('q') || `${m.alt} ${m.caption} ${p?.name}`.toLowerCase().includes(query.get('q').toLowerCase())));
    body = intro('The gallery', title, description) + `<div class="container">${filterForm(select('place', 'Places', content.places.map(p => [p.id, p.name]), query.get('place')) + select('subject', 'Subjects', [...new Set(content.media.map(m => m.subject))].filter(Boolean), query.get('subject')), '/gallery/', query)}<p class="results" role="status">${selection.length} photographs</p><section class="gallery-grid" aria-label="Curated project photographs">${selection.map(({ m, p }, index) => photoLink(m, p, { index })).join('') || '<div class="empty-state"><h2>No photographs match.</h2><a href="/gallery/">Clear filters</a></div>'}</section></div>${follow(settings)}`;
  } else if (path === '/journal/') {
    title = 'Journal'; description = 'Build updates from Marc and David.';
    body = intro('The journal', title, description, `<p class="intro-links">${link('/rss.xml', 'RSS')}${link('/progress/', 'Progress')}${link(settings.substack, 'Substack ↗')}</p>`) + `<div class="container section journal-list">${updates.map(u => updateCard(u, content)).join('') || ''}${content.articles.length ? `<section><h2>Substack</h2>${content.articles.map(a => articleCard(a, content)).join('')}</section>` : ''}</div>`;
  } else if (path.startsWith('/journal/')) {
    const u = updates.find(u => `/journal/${u.slug}/` === path);
    if (!u) return notFound();
    title = u.title; description = u.body.slice(0, 180); image = u.mediaIds[0]; const p = place(u.placeId);
    body = intro(u.kind || 'Build journal', title, '', `<p class="byline">${date(u.publishedAt)} · ${e(u.author)}${p ? ` · ${link(`/places/${p.slug}/`, p.name)}` : ''}</p>`) + `<article class="container reading journal-body">${richText(u.body)}${u.mediaIds.map(media).filter(Boolean).map(m => photoLink(m, p)).join('')}${u.stageId ? `<p>${link(`/builds/${u.stageId}/`, 'Read the original build stage →')}</p>` : ''}${p ? `<p>${link(`/places/${p.slug}/`, `Explore ${p.name} →`, 'button')}</p>` : ''}<p>${link('/journal/', 'Back to the journal')}</p></article>${follow(settings)}`;
  } else if (path.startsWith('/regions/')) {
    const region = content.regions.find(r => `/regions/${r.id}/` === path);
    if (!region || !content.places.some(p => p.regionId === region.id)) return notFound();
    title = region.name; description = region.note;
    const places = content.places.filter(p => p.regionId === region.id);
    body = intro('Around Gielinor', title, description, `<p>${badge(region.status)} · ${places.length} places</p>`) + `<div class="container section"><div class="place-grid">${places.map(p => placeCard(p, content)).join('')}</div><section class="section"><h2>Recent work in ${e(region.name)}</h2>${updates.filter(u => places.some(p => p.id === u.placeId)).slice(0, 3).map(u => updateCard(u, content)).join('')}</section>${link(`/explore/?region=${region.id}`, 'Explore this region on the atlas →')}</div>`;
  } else if (path === '/about/') {
    title = 'About'; description = 'Marc and David’s Gielinor build in Minecraft.';
    body = intro('', title, description) + `<div class="container about-layout"><div>${picture(media(settings.heroId), { sizes: '(max-width: 768px) 100vw, 800px' })}</div><div class="reading">${richText(settings.aboutCopy)}<p>${link('https://dhmorgan.substack.com/p/project-runecraft-getting-started', 'How we started ↗')}</p><div class="about-faq">${settings.faq.map(f => `<details class="faq"><summary>${e(f.question)}</summary>${richText(f.answer)}</details>`).join('')}</div><p>${link('/credits/', 'Credits →')}</p></div></div>`;
  } else if (path === '/community/') {
    title = 'Follow'; description = 'Gielinor: Reforged on Instagram and Substack.';
    body = intro('', title, description) + `<div class="container community-grid"><a class="channel-card" href="${e(safeURL(settings.instagram))}">${picture(media(settings.galleryMediaIds[1]), { sizes: '(max-width: 768px) 100vw, 700px' })}<h2>Instagram ↗</h2></a><a class="channel-card" href="${e(safeURL(settings.substack))}">${picture(media(settings.galleryMediaIds[5]), { sizes: '(max-width: 768px) 100vw, 700px' })}<h2>Substack ↗</h2></a></div><div class="container section"><p>${link('/rss.xml', 'RSS')}</p>${content.tours.length ? `<h2>Tours</h2>${content.tours.map(t => `<p>${link(`/tours/${t.slug}/`, t.title)}</p>`).join('')}` : ''}${settings.ideasEnabled ? ideaForm(content) : ''}</div>`;
  } else if (path === '/support/') {
    title = 'Support'; description = 'Support Gielinor: Reforged.';
    body = intro('', title, description) + `<div class="container support-view">${picture(media(settings.heroId), { sizes: '100vw' })}<div class="actions">${link(settings.fundraiser, 'GoFundMe ↗', 'button brass')}${link(settings.instagram, 'Instagram ↗', 'button')}</div></div>`;
  } else if (path === '/credits/' || path === '/privacy/') {
    const credits = path === '/credits/'; title = credits ? 'Credits & thanks' : 'Privacy'; description = credits ? 'The hands, tools and foundations behind Gielinor: Reforged.' : 'A small site, with a straightforward approach to your data.';
    body = intro('Gielinor: Reforged', title, description) + `<div class="container reading section">${richText(credits ? settings.creditsCopy : settings.privacyCopy)}${credits ? `<p>${link('https://www.conquestreforged.com/', 'Conquest Reforged ↗')}</p><p>${link('/licenses/literata.txt', 'Literata licence')} · ${link('/licenses/source-sans-3.txt', 'Source Sans 3 licence')}</p>` : `<h2>Your saved places</h2><p>Saved on this device.</p><button type="button" data-clear-saved>Clear saved places</button><p role="status" data-saved-status></p>${settings.ideasEnabled ? `<h2>Ideas you submit</h2><p>Ideas and optional contact details are stored privately for up to ${e(settings.retentionDays)} days. ${e(settings.ideaReviewer)} reviews the queue. Only an approved summary and separately permitted credit can appear publicly. Use Instagram to request removal and include your submission receipt.</p>` : ''}`}</div>`;
  } else if (path === '/search/') {
    title = query.get('saved') ? 'Your saved places' : 'Search the archive'; description = query.get('saved') ? 'A few places to return to. This list stays in this browser.' : 'Find a place, build stage or story.';
    const q = (query.get('q') || '').toLowerCase();
    const foundPlaces = content.places.filter(p => `${p.name} ${p.summary}`.toLowerCase().includes(q));
    const foundUpdates = updates.filter(u => `${u.title} ${u.body}`.toLowerCase().includes(q));
    body = intro('The archive', title, description) + `<div class="container section">${query.get('saved') ? `<div class="place-grid" data-saved-list>${content.places.map(p => `<div data-saved-card="${e(p.id)}" hidden>${placeCard(p, content)}</div>`).join('')}</div><p data-saved-empty>No saved places.</p><noscript><p>Enable JavaScript to read this browser’s saved list, or <a href="/explore/">browse all places</a>.</p></noscript><button type="button" data-clear-saved>Clear saved places</button><p role="status" data-saved-status></p>` : `${filterForm('', '/search/', query)}<h2>Places</h2><div class="place-grid">${foundPlaces.map(p => placeCard(p, content)).join('') || '<p>No matching places.</p>'}</div><h2>Journal</h2>${foundUpdates.map(u => `<p>${link(`/journal/${u.slug}/`, u.title)}</p>`).join('') || '<p>No matching updates.</p>'}<h2>Build stages</h2>${content.stages.filter(s => `${s.publicTitle} ${s.notes}`.toLowerCase().includes(q)).map(s => `<p>${link(`/builds/${s.id}/`, s.publicTitle)}</p>`).join('') || '<p>No matching stages.</p>'}`}</div>`;
  } else if (path.startsWith('/tours/')) {
    const tour = content.tours.find(t => `/tours/${t.slug}/` === path && t.state === 'published');
    if (!tour) return notFound();
    title = tour.title; description = tour.summary;
    body = intro('A guided visit', title, description) + `<div class="container reading section">${tour.stops.map((stop, i) => { const p = place(stop.placeId); return `<section id="stop-${i + 1}"><p class="eyebrow">Stop ${i + 1} of ${tour.stops.length}</p><h2>${e(p.name)}</h2>${photoLink(media(stop.mediaId || p.coverId), p)}${i + 1 < tour.stops.length ? `<a href="#stop-${i + 2}">Next stop ↓</a>` : link('/community/', 'Follow →')}</section>`; }).join('')}</div>`;
  } else return notFound();
  return { title, description, body, image: media(image), status, path };
}
function ideaForm(content) { return `<form id="idea-form" class="idea-form"><h3>Suggest a detail</h3><label>Which place?<select name="placeId">${content.places.map(p => `<option value="${e(p.id)}">${e(p.name)}</option>`).join('')}</select></label><label>What should we look at?<textarea name="text" required maxlength="3000"></textarea></label><label>Reference link (optional)<input type="url" name="reference" maxlength="1000"></label><label>Email for a reply (optional)<input type="email" name="email" maxlength="254"></label><label>Display name (optional)<input name="displayName" maxlength="80"></label><label class="checkbox"><input type="checkbox" name="creditConsent">You may credit this display name publicly.</label><label class="checkbox"><input type="checkbox" name="summaryConsent">You may publish a reviewed summary of this idea.</label><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p><a href="/privacy/">Privacy</a></p><button type="submit">Send idea</button><p role="status" data-form-status></p></form>`; }
export function notFound() { return { status: 404, title: 'Page not found', description: 'This place or story could not be found.', path: '/404/', body: `${intro('', 'Page not found', '')}<div class="container reading section"><div class="actions">${link('/explore/', 'Explore the builds', 'button')}${link('/search/', 'Search the archive', 'button')}</div></div>` }; }
export function shell(page, content, { source = 'live', stale = false, preview = false } = {}) {
  const { settings } = viewContext(content);
  const active = page.path.split('/')[1];
  return `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container header-inner"><a href="/" class="wordmark" aria-label="Gielinor: Reforged home"><img src="/brand/logo.webp" width="1200" height="630" alt="Gielinor: Reforged"></a><button class="menu-toggle" type="button" aria-controls="primary-nav" aria-expanded="false">Menu <span aria-hidden="true">☰</span></button><nav id="primary-nav" aria-label="Primary navigation">${[['explore', 'Explore'], ['journal', 'Journal'], ['gallery', 'Gallery'], ['about', 'About']].map(([route, label]) => `<a href="/${route}/" ${active === route || (route === 'explore' && ['places', 'regions', 'builds', 'progress'].includes(active)) ? 'aria-current="page"' : ''}>${e(settings.navLabels?.[route] || label)}</a>`).join('')}${link('/community/', 'Follow', 'nav-follow')}</nav></div></header>${preview ? '<p class="publication-banner">Private preview</p>' : stale ? `<p class="publication-banner" role="status">Offline copy · ${e(formatDate(content.publishedAt || content.snapshotAt))} · <a href="${e(page.path)}">Retry</a></p>` : ''}<main id="main" tabindex="-1">${page.body}</main><footer class="site-footer"><div class="container"><div class="footer-top"><div><a class="footer-brand" href="/"><img src="/brand/logo.webp" width="1200" height="630" alt="Gielinor: Reforged" loading="lazy"></a></div><nav aria-label="Footer navigation">${link('/support/', 'Support')}${link('/credits/', 'Credits')}${link('/privacy/', 'Privacy')}${link('/search/', 'Search')}${link('/rss.xml', 'RSS')}${link('/admin/', 'Author access')}</nav></div><div class="footer-fine">${link(settings.instagram, 'Instagram ↗')}${link(settings.substack, 'Substack ↗')}</div></div></footer><dialog id="photo-viewer" aria-labelledby="viewer-caption"><div class="viewer-toolbar"><span id="viewer-count"></span><button type="button" data-viewer-close aria-label="Close photograph viewer">Close ×</button></div><div class="viewer-image-wrap"><button type="button" data-viewer-prev aria-label="Previous photograph">←</button><img id="viewer-image" alt=""><button type="button" data-viewer-next aria-label="Next photograph">→</button></div><div class="viewer-bottom"><p id="viewer-caption"></p><p id="viewer-credit"></p><a id="viewer-place" href="/gallery/">Explore this place</a><button type="button" data-share-photo>Copy photograph link</button><p role="status" id="viewer-status"></p></div></dialog>`;
}
