const {test,expect}=require('@playwright/test');
test('standalone atlas pans, zooms, opens complete tickets and dismisses selections',async({page},info)=>{
  await page.goto('/atlas/?place=draynor-village');const viewport=page.locator('.map-viewport'),canvas=page.locator('.map-canvas');await expect(viewport).toHaveAttribute('data-zoom',/\d/);const startZoom=await viewport.getAttribute('data-zoom');await expect(page.locator('.atlas-popup')).toBeVisible();await page.getByRole('link',{name:'Close map popup'}).click();await expect(page.locator('.atlas-popup')).toBeHidden();
  await page.locator('[data-pin="draynor-village"]').click();await expect(page.locator('.atlas-popup')).toContainText('Draynor Village');await page.locator('[data-popup-ticket]').selectOption('draynor-village-interior-build');await expect(page.locator('[data-popup-build="draynor-village-interior-build"] a')).toHaveAttribute('href','/builds/draynor-village-interior-build/');await page.keyboard.press('Escape');await expect(page.locator('.atlas-popup')).toBeHidden();
  const box=await viewport.boundingBox(),dragY=Math.min(box.y+box.height*.65,page.viewportSize().height-50);await page.mouse.move(box.x+30,dragY);const before=await canvas.getAttribute('style');await page.mouse.down();await page.mouse.move(box.x+90,dragY-55,{steps:8});await page.mouse.up();await expect(canvas).not.toHaveAttribute('style',before);
  if(info.project.name==='webkit-phone')await page.getByRole('button',{name:'Zoom map in',exact:true}).click();else await page.mouse.wheel(0,-250);await expect(viewport).not.toHaveAttribute('data-zoom',startZoom);await page.getByRole('button',{name:'Reset',exact:true}).click();await expect(viewport).toHaveAttribute('data-zoom','1.000');
  if(info.project.name==='chromium-phone'){const cdp=await page.context().newCDPSession(page),y=dragY;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+100,y,id:1},{x:box.x+180,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+70,y,id:1},{x:box.x+210,y,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(async()=>Number(await viewport.getAttribute('data-zoom'))).toBeGreaterThan(1);await cdp.detach();}
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('Explore views preserve identical filters and gallery cascades region to place',async({page})=>{
  await page.goto('/explore/?q=Lumbridge&region=misthalin&status=Built&sort=oldest');await page.getByRole('link',{name:'Build Board',exact:true}).click();await expect(page.locator('[name=q]')).toHaveValue('Lumbridge');await expect(page.locator('[name=region]')).toHaveValue('misthalin');await expect(page.locator('[name=status]')).toHaveValue('Built');await expect(page.locator('[name=sort]')).toHaveValue('oldest');
  await page.getByRole('link',{name:'Full View',exact:true}).click();await expect(page.locator('.completion-date').first()).toContainText('Completion date:');
  await page.goto('/gallery/?place=draynor-village');await page.getByLabel('Region',{exact:true}).selectOption('asgarnia');await expect(page).toHaveURL(/region=asgarnia/);await expect(page.locator('[name=place] option')).toHaveCount(1);await expect(page.locator('[data-photo]')).toHaveCount(0);
});
