const {test,expect}=require('@playwright/test');
test.beforeEach(async({},info)=>test.skip(info.project.name!=='chromium-desktop','Publication scenarios use one isolated writer.'));
async function login(page){await page.goto('/admin/');await page.getByLabel('Access key').fill('local-e2e-project-key');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Build tickets',exact:true})).toBeVisible();}
async function addTicket(page,title){await page.getByRole('button',{name:'Add build ticket',exact:true}).click();await page.getByLabel('Ticket title',{exact:true}).fill(title);}
async function chooseLumbridge(page){await page.getByLabel('Find a place',{exact:true}).fill('Lumbridge');await page.locator('[data-choose-place="lumbridge"]').click();}
test('two tickets reuse one canonical place and publish complete ticket photos without deployment',async({page})=>{
  await login(page);await addTicket(page,'Lumbridge market stalls');await chooseLumbridge(page);await page.getByLabel('Status',{exact:true}).selectOption('Built');await page.getByLabel('Completion date',{exact:true}).fill('2026-09-09');await page.getByLabel('Build notes',{exact:true}).fill('The market stalls and their interiors.');
  await page.getByText('Choose from the media library',{exact:true}).click();for(const box of (await page.locator('[data-select-media]').all()).slice(0,2))await box.check();
  await page.getByRole('button',{name:'Preview ticket',exact:true}).click();await expect(page.frameLocator('iframe').locator('h1')).toHaveText('Lumbridge market stalls');await page.getByRole('button',{name:'Close ×',exact:true}).click();
  await page.getByRole('button',{name:'Add ticket to website',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Saved to website and verified');await expect(page.getByRole('heading',{name:'Editing published ticket',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'All build tickets',exact:false}).click();await addTicket(page,'Lumbridge market paths');await chooseLumbridge(page);await page.getByLabel('Build notes',{exact:true}).fill('Paths between the stalls.');await page.getByRole('button',{name:'Add ticket to website',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Saved to website and verified');
  const {content}=await (await page.request.get('/api/content')).json();const tickets=content.stages.filter(s=>s.publicTitle.startsWith('Lumbridge market'));
  expect(tickets).toHaveLength(2);expect(tickets.every(s=>s.placeId==='lumbridge')).toBe(true);expect(content.places.filter(p=>p.name==='Lumbridge')).toHaveLength(1);
  const first=tickets.find(t=>t.publicTitle==='Lumbridge market stalls');const html=await (await page.request.get(`/builds/${first.id}/`)).text();expect(html).toContain('The market stalls and their interiors.');expect(html).toContain('9 September 2026');expect(first.mediaIds).toHaveLength(2);
});
test('ticket place lookup creates a place once and offers it for reuse',async({page})=>{
  await login(page);await addTicket(page,'Varrock south gate');await page.getByLabel('Find a place',{exact:true}).fill('South Varrock');await page.getByRole('button',{name:'Create a new place',exact:true}).click();await page.getByRole('button',{name:'Use new place',exact:true}).click();await page.getByRole('button',{name:'Add ticket to website',exact:true}).click();await expect(page.locator('#editor-status')).toContainText('Saved to website and verified');
  await page.getByRole('button',{name:'All build tickets',exact:false}).click();await addTicket(page,'Varrock gatehouse');await page.getByLabel('Find a place',{exact:true}).fill('South Varrock');await expect(page.locator('[data-choose-place="south-varrock"]')).toBeVisible();await expect(page.getByRole('button',{name:'Create a new place',exact:true})).toHaveCount(0);
});
test('new server version blocks a stale ticket save and offers published content first',async({page})=>{
  await login(page);await page.locator('[data-edit-ticket="lumbridge-castle-foundations-and-exterior-build"]').click();await page.getByLabel('Build notes',{exact:true}).fill('Stale local text must not replace the website.');
  const workspace=await (await page.request.get('/api/workspace')).json(),content=workspace.content;content.stages.find(s=>s.id==='lumbridge-castle-foundations-and-exterior-build').notes='New server build notes';
  const result=await page.request.post('/api/publish',{headers:{Origin:'http://127.0.0.1:4378'},data:{content,baseRevision:content.revision,requestId:'stale-ticket-'+Date.now(),requireCurrent:true}});expect(result.status()).toBe(200);
  await page.getByRole('button',{name:'Save ticket to website',exact:true}).click();await expect(page.locator('#stale-dialog')).toBeVisible();await page.context().clearCookies();await page.getByRole('button',{name:'Load published version',exact:true}).click();await expect(page.getByRole('heading',{name:'Sign in again',exact:true})).toBeVisible();await page.getByLabel('Access key').fill('local-e2e-project-key');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.locator('#stale-dialog')).toBeVisible();await page.getByRole('button',{name:'Load published version',exact:true}).click();await expect(page.locator('#stale-dialog')).toHaveCount(0);await page.locator('[data-edit-ticket="lumbridge-castle-foundations-and-exterior-build"]').click();await expect(page.getByLabel('Build notes',{exact:true})).toHaveValue('New server build notes');
});
test('local ticket recovery is optional and clearly separate from published content',async({page})=>{
  await login(page);await addTicket(page,'Unpublished ticket recovery');await chooseLumbridge(page);await page.getByLabel('Build notes',{exact:true}).fill('Keep this local until explicitly saved.');await expect(page.locator('[data-autosave]')).toContainText('Saved on this device');await page.reload();await expect(page.getByRole('button',{name:'Use published version',exact:true})).toBeVisible();await expect(page.locator('#ticket-form')).toHaveCount(0);await page.getByRole('button',{name:'Recover local changes',exact:true}).click();await expect(page.getByLabel('Ticket title',{exact:true})).toHaveValue('Unpublished ticket recovery');expect(await (await page.request.get('/api/content')).text()).not.toContain('Unpublished ticket recovery');
});
test('published updates can be found, archived, and restored from a dedicated list',async({page})=>{
  await login(page);await page.getByRole('button',{name:'Published updates',exact:true}).click();await page.getByLabel('Find an update',{exact:true}).fill('Draynor');const button=page.locator('[data-archive-note]').first(),id=await button.getAttribute('data-archive-note');await button.click();await expect(page.locator('#editor-status')).toContainText('Saved to website and verified');await page.getByLabel('Publication',{exact:true}).selectOption('archived');await expect(page.locator(`[data-archive-note="${id}"]`)).toHaveText('Restore update');await page.locator(`[data-archive-note="${id}"]`).click();await expect(page.locator('#editor-status')).toContainText('Saved to website and verified');
});
